-- Reder: cse340 Database
-- Database: cse340
-- user: admin


-- Type: account_type

-- DROP TYPE IF EXISTS public.account_type;

CREATE TYPE public.account_type AS ENUM
    ('Client', 'Employee', 'Admin');

ALTER TYPE public.account_type
    OWNER TO admin;


-- Table structure for table `classification`

CREATE TABLE public.classification (
    classification_id INT GENERATED BY DEFAULT AS IDENTITY,
    classification_name CHARACTER VARYING NOT NULL,
    CONSTRAINT classification_pk PRIMARY KEY (classification_id)
);

-- Table structure for table `inventory`
CREATE TABLE IF NOT EXISTS public.inventory
(
    inv_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    inv_make character varying NOT NULL,
    inv_model character varying NOT NULL,
    inv_year character(4) NOT NULL,
    inv_description text NOT NULL,
    inv_image character varying NOT NULL,
    inv_thumbnail character varying NOT NULL,
    inv_price numeric(9, 0) NOT NULL,
    inv_miles integer NOT NULL,
    inv_color character varying NOT NULL,
    classification_id integer NOT NULL,
    CONSTRAINT inventory_pkey PRIMARY KEY (inv_id)
);

-- Create relationship between `classification` and `inventory` tables
ALTER TABLE IF EXISTS public.inventory
    ADD CONSTRAINT fk_classification FOREIGN KEY (classification_id)
    REFERENCES public.classification (classification_id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE NO ACTION;

	-- Table structure for table `account`
CREATE TABLE IF NOT EXISTS public.account
(
    account_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    account_firstname character varying NOT NULL,
    account_lastname character varying NOT NULL,
    account_email character varying NOT NULL,
    account_password character varying NOT NULL,
    account_type account_type NOT NULL DEFAULT 'Client'::account_type,
    CONSTRAINT account_pkey PRIMARY KEY (account_id)
);

/* 1) Create Tony Stark*/
INSERT INTO public.account (
  account_firstname,
  account_lastname,
  account_email,
  account_password
) VALUES (
  'Tony',
  'Stark',
  'tony@starkent.com',
  'Iam1ronM@n'
);
-- 2) Modify Tony Stark to Admin
UPDATE public.account
SET account_type = 'Admin'::account_type
WHERE account_firstname = 'Tony'
  AND account_lastname  = 'Stark'
  AND account_email     = 'tony@starkent.com';

-- 2) Delete Tony Stark
DELETE FROM  public.account
WHERE account_firstname = 'Tony'
  AND account_lastname  = 'Stark'
  AND account_email     = 'tony@starkent.com';

--SELECT * from public.account 

-- Data for table `classification`
INSERT INTO public.classification (classification_name)
VALUES ('Custom'),
    ('Sport'),
    ('SUV'),
    ('Truck'),
    ('Sedan');


-- Insert data into the inventory table
-- TRUNCATE TABLE public.inventory
INSERT INTO public.inventory (
    inv_make,
    inv_model,
    inv_year,
    inv_description,
    inv_image,
    inv_thumbnail,
    inv_price,
    inv_miles,
    inv_color,
    classification_id
)
VALUES
    (
        'Chevy',
        'Camaro',
        '2018',
        'This beautiful Chevy Camaro is a joy to drive. It features a V8 engine, leather seats, and a premium sound system. Perfect for cruising on the weekends.',
        '/images/camaro.jpg',
        '/images/camaro-tn.jpg',
        25000,
        101222,
        'Silver',
        2
    ),
    (
        'Ford',
        'F-150',
        '2022',
        'The Ford F-150 is the best-selling truck in America for a reason. This model comes with a powerful EcoBoost engine, a spacious crew cab, and advanced towing technology.',
        '/images/f150.jpg',
        '/images/f150-tn.jpg',
        55000,
        15000,
        'White',
        4
    ),
    (
        'Honda',
        'Civic',
        '2020',
        'A reliable and fuel-efficient sedan, the Honda Civic is perfect for daily commuting. It includes features like Apple CarPlay, a rearview camera, and Honda Sensing safety technology.',
        '/images/civic.jpg',
        '/images/civic-tn.jpg',
        22000,
        30000,
        'Blue',
        5
    ),
    (
        'Jeep',
        'Wrangler',
        '2021',
        'Ready for any adventure, the Jeep Wrangler is an iconic SUV with unmatched off-road capabilities. This model has a removable top and doors for the ultimate open-air experience.',
        '/images/wrangler.jpg',
        '/images/wrangler-tn.jpg',
        40000,
        20000,
        'Red',
        3
    ),
    (
        'Toyota',
        'Camry',
        '2023',
        'The Toyota Camry offers a smooth ride, excellent fuel economy, and a spacious interior. This latest model includes a large touchscreen display and advanced driver-assist features.',
        '/images/camry.jpg',
        '/images/camry-tn.jpg',
        28000,
        5000,
        'Black',
        5
    ),
    (
        'Dodge',
        'Charger',
        '2020',
        'A modern muscle car with four doors, the Dodge Charger combines performance and practicality. It boasts a powerful HEMI V8 engine and a comfortable, tech-filled cabin.',
        '/images/charger.jpg',
        '/images/charger-tn.jpg',
        35000,
        25000,
        'Gray',
        2
    ),
    (
        'Nissan',
        'Titan',
        '2019',
        'A full-size truck with a standard V8 engine, the Nissan Titan is built for tough jobs. It features a durable bed, a comfortable ride, and a 5-year/100,000-mile warranty.',
        '/images/titan.jpg',
        '/images/titan-tn.jpg',
        32000,
        45000,
        'Brown',
        4
    ),
    (
        'Subaru',
        'Outback',
        '2022',
        'The Subaru Outback is a versatile SUV with standard all-wheel drive, making it perfect for all weather conditions. It offers ample cargo space and advanced safety features.',
        '/images/outback.jpg',
        '/images/outback-tn.jpg',
        33000,
        18000,
        'Green',
        3
    ),
    (
        'BMW',
        '3 Series',
        '2021',
        'A luxury sport sedan that delivers an engaging driving experience. The BMW 3 Series features a turbocharged engine, premium interior materials, and cutting-edge technology.',
        '/images/3series.jpg',
        '/images/3series-tn.jpg',
        45000,
        22000,
        'White',
        5
    ),
    (
        'Mercedes-Benz',
        'C-Class',
        '2020',
        'The Mercedes-Benz C-Class is a stylish and comfortable luxury sedan. It comes with a refined interior, a smooth ride, and a host of advanced technology and safety features.',
        '/images/c-class.jpg',
        '/images/c-class-tn.jpg',
        42000,
        28000,
        'Silver',
        5
    ),
    (
        'GMC',
        'Sierra',
        '2021',
        'The GMC Sierra is a premium full-size truck that offers a comfortable and quiet ride. This model includes the innovative MultiPro Tailgate and a luxurious Denali trim.',
        '/images/sierra.jpg',
        '/images/sierra-tn.jpg',
        58000,
        12000,
        'Black',
        4
    ),
    (
        'Lamborghini',
        'Huracan',
        '2022',
        'An exotic sports car with breathtaking performance and head-turning style. The Lamborghini Huracan features a V10 engine, all-wheel drive, and a driver-focused cockpit.',
        '/images/huracan.jpg',
        '/images/huracan-tn.jpg',
        250000,
        3000,
        'Yellow',
        2
    ),
    (
        'GM',
        'Hummer',
        '2003',
        'The Hummer GM has small interiors, rugged SUV with a commanding presence on the road. It offers exceptional off-road capability and a spacious, utilitarian interior.',
        '/images/h2.jpg',
        '/images/h2-tn.jpg',
        20000,
        150000,
        'Black',
        3
    ),
    (
        'Batmobile',
        'Tumbler',
        '2005',
        'The Tumbler is a custom-built, military-grade vehicle used by Batman. It features advanced weaponry, armor plating, and a powerful jet engine for high-speed pursuits.',
        '/images/tumbler.jpg',
        '/images/tumbler-tn.jpg',
        1000000,
        5000,
        'Black',
        1
    ),
    (
        'Mystery',
        'Machine',
        '1969',
        'The iconic van of Mystery, Inc., this vehicle has been customized for ghost-hunting adventures. It comes equipped with tracking computers, antennas, and other gadgets.',
        '/images/mystery-machine.jpg',
        '/images/mystery-machine-tn.jpg',
        15000,
        200000,
        'Multi-colored',
        1
    );

--4)  Update the description for the GM Hummer
select inv_description FROM inventory WHERE inv_make = 'GM' AND inv_model = 'Hummer';
UPDATE
  inventory
SET
  inv_description = REPLACE(inv_description, 'small interiors', 'a huge interior')
WHERE
  inv_make = 'GM' AND inv_model = 'Hummer';

 
--5): Select Sport category vehicles using an INNER JOIN
SELECT
  inv.inv_make,
  inv.inv_model,
  cla.classification_name
FROM
  inventory AS inv
INNER JOIN
  classification AS cla ON inv.classification_id = cla.classification_id
WHERE
  cla.classification_name = 'Sport';

--6): Add '/vehicles' to all image and thumbnail paths
UPDATE
  inventory
SET
  inv_image = REPLACE(inv_image, '/images/', '/images/vehicles/'),
  inv_thumbnail = REPLACE(inv_thumbnail, '/images/', '/images/vehicles/');
